repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: debug-statements
        language_version: python3.10
      - id: name-tests-test
        args: [ "--django" ]
#      - id: no-commit-to-branch
#        args: [ --branch, main ]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        additional_dependencies: [ types-pytz, types-requests, types-redis ]
  - repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
