version: 2

mkdocs:
  configuration: kova-docs/mkdocs.yml
  fail_on_warning: false
  
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: kova-docs/requirements.txt
