version: "3.5"
services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: [ "nats" ]
  nats-1:
    image: nats
    ports:
      - "5222:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: [ "nats" ]
    depends_on: [ "nats" ]
  nats-2:
    image: nats
    ports:
      - "6222:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: [ "nats" ]
    depends_on: [ "nats" ]

  db:
    image: postgres:11-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: kova-test
      POSTGRES_USER: kova-test
      POSTGRES_DB: kova-test

networks:
  nats:
    name: nats
