# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto

import sys

_b = (
    sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
)
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="image.proto",
    package="echo",
    syntax="proto3",
    serialized_pb=_b(
        '\n\x0bimage.proto\x12\x04\x65\x63ho"\x1c\n\x0cImageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t"!\n\x11ImageConfirmation\x12\x0c\n\x04name\x18\x01 \x01(\t"\x1c\n\rImageResponse\x12\x0b\n\x03URL\x18\x01 \x01(\t"+\n\x0eTransformation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03URL\x18\x02 \x01(\t"S\n\x15ModifiedImageResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12,\n\x0etransformation\x18\x02 \x03(\x0b\x32\x14.echo.Transformationb\x06proto3'
    ),
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


_IMAGEREQUEST = _descriptor.Descriptor(
    name="ImageRequest",
    full_name="echo.ImageRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="echo.ImageRequest.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=21,
    serialized_end=49,
)


_IMAGECONFIRMATION = _descriptor.Descriptor(
    name="ImageConfirmation",
    full_name="echo.ImageConfirmation",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="echo.ImageConfirmation.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=51,
    serialized_end=84,
)


_IMAGERESPONSE = _descriptor.Descriptor(
    name="ImageResponse",
    full_name="echo.ImageResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="URL",
            full_name="echo.ImageResponse.URL",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=86,
    serialized_end=114,
)


_TRANSFORMATION = _descriptor.Descriptor(
    name="Transformation",
    full_name="echo.Transformation",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="echo.Transformation.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="URL",
            full_name="echo.Transformation.URL",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=116,
    serialized_end=159,
)


_MODIFIEDIMAGERESPONSE = _descriptor.Descriptor(
    name="ModifiedImageResponse",
    full_name="echo.ModifiedImageResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="echo.ModifiedImageResponse.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="transformation",
            full_name="echo.ModifiedImageResponse.transformation",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=161,
    serialized_end=244,
)

_MODIFIEDIMAGERESPONSE.fields_by_name[
    "transformation"
].message_type = _TRANSFORMATION
DESCRIPTOR.message_types_by_name["ImageRequest"] = _IMAGEREQUEST
DESCRIPTOR.message_types_by_name["ImageConfirmation"] = _IMAGECONFIRMATION
DESCRIPTOR.message_types_by_name["ImageResponse"] = _IMAGERESPONSE
DESCRIPTOR.message_types_by_name["Transformation"] = _TRANSFORMATION
DESCRIPTOR.message_types_by_name[
    "ModifiedImageResponse"
] = _MODIFIEDIMAGERESPONSE

ImageRequest = _reflection.GeneratedProtocolMessageType(
    "ImageRequest",
    (_message.Message,),
    dict(
        DESCRIPTOR=_IMAGEREQUEST,
        __module__="image_pb2"
        # @@protoc_insertion_point(class_scope:echo.ImageRequest)
    ),
)
_sym_db.RegisterMessage(ImageRequest)

ImageConfirmation = _reflection.GeneratedProtocolMessageType(
    "ImageConfirmation",
    (_message.Message,),
    dict(
        DESCRIPTOR=_IMAGECONFIRMATION,
        __module__="image_pb2"
        # @@protoc_insertion_point(class_scope:echo.ImageConfirmation)
    ),
)
_sym_db.RegisterMessage(ImageConfirmation)

ImageResponse = _reflection.GeneratedProtocolMessageType(
    "ImageResponse",
    (_message.Message,),
    dict(
        DESCRIPTOR=_IMAGERESPONSE,
        __module__="image_pb2"
        # @@protoc_insertion_point(class_scope:echo.ImageResponse)
    ),
)
_sym_db.RegisterMessage(ImageResponse)

Transformation = _reflection.GeneratedProtocolMessageType(
    "Transformation",
    (_message.Message,),
    dict(
        DESCRIPTOR=_TRANSFORMATION,
        __module__="image_pb2"
        # @@protoc_insertion_point(class_scope:echo.Transformation)
    ),
)
_sym_db.RegisterMessage(Transformation)

ModifiedImageResponse = _reflection.GeneratedProtocolMessageType(
    "ModifiedImageResponse",
    (_message.Message,),
    dict(
        DESCRIPTOR=_MODIFIEDIMAGERESPONSE,
        __module__="image_pb2"
        # @@protoc_insertion_point(class_scope:echo.ModifiedImageResponse)
    ),
)
_sym_db.RegisterMessage(ModifiedImageResponse)


# @@protoc_insertion_point(module_scope)
