# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto

import sys

_b = (
    sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
)
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="image.proto",
    package="echo",
    syntax="proto3",
    serialized_pb=_b(
        '\n\x0bimage.proto\x12\x04\x65\x63ho"2\n\x0cImageRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x63onfirmation\x18\x02 \x01(\x08"\x1c\n\rImageResponse\x12\x0b\n\x03URL\x18\x01 \x01(\t"V\n\x15ImageModifiedResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x19\n\x11image_cropped_URL\x18\x02 \x01(\t\x12\x14\n\x0cimage_BW_URL\x18\x03 \x01(\tb\x06proto3'
    ),
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


_IMAGEREQUEST = _descriptor.Descriptor(
    name="ImageRequest",
    full_name="echo.ImageRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="echo.ImageRequest.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="confirmation",
            full_name="echo.ImageRequest.confirmation",
            index=1,
            number=2,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=21,
    serialized_end=71,
)


_IMAGERESPONSE = _descriptor.Descriptor(
    name="ImageResponse",
    full_name="echo.ImageResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="URL",
            full_name="echo.ImageResponse.URL",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=73,
    serialized_end=101,
)


_IMAGEMODIFIEDRESPONSE = _descriptor.Descriptor(
    name="ImageModifiedResponse",
    full_name="echo.ImageModifiedResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="echo.ImageModifiedResponse.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="image_cropped_URL",
            full_name="echo.ImageModifiedResponse.image_cropped_URL",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
        _descriptor.FieldDescriptor(
            name="image_BW_URL",
            full_name="echo.ImageModifiedResponse.image_BW_URL",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=103,
    serialized_end=189,
)

DESCRIPTOR.message_types_by_name["ImageRequest"] = _IMAGEREQUEST
DESCRIPTOR.message_types_by_name["ImageResponse"] = _IMAGERESPONSE
DESCRIPTOR.message_types_by_name[
    "ImageModifiedResponse"
] = _IMAGEMODIFIEDRESPONSE

ImageRequest = _reflection.GeneratedProtocolMessageType(
    "ImageRequest",
    (_message.Message,),
    dict(
        DESCRIPTOR=_IMAGEREQUEST,
        __module__="image_pb2"
        # @@protoc_insertion_point(class_scope:echo.ImageRequest)
    ),
)
_sym_db.RegisterMessage(ImageRequest)

ImageResponse = _reflection.GeneratedProtocolMessageType(
    "ImageResponse",
    (_message.Message,),
    dict(
        DESCRIPTOR=_IMAGERESPONSE,
        __module__="image_pb2"
        # @@protoc_insertion_point(class_scope:echo.ImageResponse)
    ),
)
_sym_db.RegisterMessage(ImageResponse)

ImageModifiedResponse = _reflection.GeneratedProtocolMessageType(
    "ImageModifiedResponse",
    (_message.Message,),
    dict(
        DESCRIPTOR=_IMAGEMODIFIEDRESPONSE,
        __module__="image_pb2"
        # @@protoc_insertion_point(class_scope:echo.ImageModifiedResponse)
    ),
)
_sym_db.RegisterMessage(ImageModifiedResponse)


# @@protoc_insertion_point(module_scope)
