# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0blogin.proto\x12\x05login"A\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x15\n\x08mfa_code\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_mfa_code"&\n\rLoginResponse\x12\x15\n\rrefresh_token\x18\x01 \x01(\t"+\n\x12\x41\x63\x63\x65ssTokenRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t"+\n\x13\x41\x63\x63\x65ssTokenResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\tb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "login_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _LOGINREQUEST._serialized_start = 22
    _LOGINREQUEST._serialized_end = 87
    _LOGINRESPONSE._serialized_start = 89
    _LOGINRESPONSE._serialized_end = 127
    _ACCESSTOKENREQUEST._serialized_start = 129
    _ACCESSTOKENREQUEST._serialized_end = 172
    _ACCESSTOKENRESPONSE._serialized_start = 174
    _ACCESSTOKENRESPONSE._serialized_end = 217
# @@protoc_insertion_point(module_scope)
